/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      fontFamily: {
        'instrument-serif': ['Instrument Serif', 'serif'],
        'safiro': ['Safiro-Regular', 'sans-serif'],
        'space-mono': ['Space Mono', 'sans-serif'],
        'reckless': ['Reckless-Regular', 'sans-serif'],
      },
      colors: {
        light: {
          'paper': '#e1e6e2',
          'ink': '#0c3532',
          'ink-secondary': '#5b5376',
          'ink-reverse': '#f4f8f5',
          'ink-dark': '#0c3532',
          'stroke': '#c8d1ca',
          'surface-light': '#f4f8f5',
          'surface-medium': '#cdd9cf',
          'surface-dark': '#0c3532',
          'surface-white': '#FFFFFF',
          'highlight-lilac': '#B099F8',
          'highlight-mint': '#9fe4d0',
          'highlight-pink': '#D072D5',
          'highlight-orange': '#ff5722',
        },
        grape: {
          'paper': '#fcfbff',
          'ink': '#0d0527',
          'ink-secondary': '#3b3355',
          'ink-reverse': '#fcfbff',
          'ink-dark': '#0d0527',
          'stroke': '#cdd9cf',
          'surface-light': '#eeeaf9',
          'surface-medium': '#cab9ff',
          'surface-dark': '#0d0527',
          'surface-white': '#FFFFFF',
          'highlight-lilac': '#B099F8',
          'highlight-mint': '#9fe4d0',
          'highlight-pink': '#D072D5',
          'highlight-orange': '#ff5722',
        },
        dark: {
          'paper': '#031B1A',
          'ink': '#E1FED4',
          'ink-secondary': '#5b5376',
          'ink-reverse': '#E1FED4',
          'ink-dark': '#031B1A',
          'stroke': '#cdd9cf',
          'surface-light': '#042928',
          'surface-medium': '#0A4542',
          'surface-dark': '#010D0C',
          'surface-white': '#FFFFFF',
          'highlight-lilac': '#B099F8',
          'highlight-mint': '#063b2c',
          'highlight-pink': '#D072D5',
          'highlight-orange': '#ff5722',
        },
      },
      backgroundColor: {
        'theme-paper': 'var(--color-paper)',
        'theme-surface-light': 'var(--color-surface-light)',
        'theme-surface-medium': 'var(--color-surface-medium)',
        'theme-surface-dark': 'var(--color-surface-dark)',
        'theme-surface-white': 'var(--color-surface-white)',
        'theme-highlight-lilac': 'var(--color-highlight-lilac)',
        'theme-highlight-mint': 'var(--color-highlight-mint)',
        'theme-highlight-pink': 'var(--color-highlight-pink)',
        'theme-highlight-orange': 'var(--color-highlight-orange)',
      },
      textColor: {
        'theme-ink': 'var(--color-ink)',
        'theme-ink-secondary': 'var(--color-ink-secondary)',
        'theme-ink-reverse': 'var(--color-ink-reverse)',
        'theme-ink-dark': 'var(--color-ink-dark)',
        'theme-highlight-lilac': 'var(--color-highlight-lilac)',
        'theme-highlight-mint': 'var(--color-highlight-mint)',
        'theme-highlight-pink': 'var(--color-highlight-pink)',
        'theme-highlight-orange': 'var(--color-highlight-orange)',
      },
      borderColor: {
        'theme-stroke': 'var(--color-stroke)',
      },
      gradientColorStops: {
        'theme-paper': 'var(--color-paper)',
      },
      zIndex: {
        'minimal': '1',
        'base': '10',
        'navigation': '20',
        'menu': '30',
      },
      gridTemplateColumns: {
        '26': 'repeat(26, minmax(0, 1fr))',
        '24': 'repeat(24, minmax(0, 1fr))',
      },
      gridColumnEnd: {
        '24': '24',
        '22': '22',
        '20': '20',
      },
      screens: {
        'base': '1600px',
        'base-md': '1200px',
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-in-out',
        'fade-in-up': 'fade-in-up 0.5s ease-in-out',
        'fade-in-down': 'fade-in-down 0.5s ease-in-out',
        'fade-in-left': 'fade-in-left 0.5s ease-in-out',
        'fade-in-right': 'fade-in-right 0.5s ease-in-out',
        'slow-fade-in': 'slow-fade-in 1.5s ease-in-out',
        'spin-slow': 'spin 10s linear infinite',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(100%)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-down': {
          '0%': { opacity: '0', transform: 'translateY(-100%)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in-left': {
          '0%': { opacity: '0', transform: 'translateX(-100%)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'fade-in-right': {
          '0%': { opacity: '0', transform: 'translateX(100%)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slow-fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'spin-slow': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
} 